### ISSUE TITLE
GCE Internal DNS Changed

### ISSUE THREAD

**Issue by jordxn** [WPO-Foundation/wptserver-install#1]
Hi,

Currently the server urls are being generated as;
[INSTANCE_NAME].c.[PROJECT_ID].internal

but as of Sept 6th, 2018 this has changed to;
[INSTANCE_NAME].[ZONE].c.[PROJECT_ID].internal

see https://cloud.google.com/compute/docs/internal-dns

So we need to include the zone of the server in the generated URL for the agents.

**Comment by pmeenan** [comment]
Looks like the metadata service provides the full internal hostname appropriate for the account so no need to generate it manually.
